"""Issue #33: does a chat history compressed to L1 pull the model's Japanese answers toward the L1 style?

Scenario: a 8-exchange chat in which the user talks about friends (target person with a status such as "undecided", plus
distractor people and small talk); the final user message asks for advice about the target person. The target facts are in the
OLDEST exchanges, so with an L1-compressed old history they reach the model only as L1. The old assistant replies were
generated once by gemma-4-12b from the L0 history (polite register persona).

Prompt families (the final user turn is always natural L0):
  role  : the history is sent as chat messages; the oldest c exchanges contain L1 text (c=0 baseline, c=8 = Full L1)
  tag   : system persona (+ isolation rules) and ONE user message with <compressed_context> (L1 text of the oldest c exchanges),
          <recent_conversation> (the rest, L0) and the question; variants: instruction off, recent/compressed order, persona after block
"""
from __future__ import annotations

import json
import random
import re
import sys
import time
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

from . import jl1, jlvar, jpdata
from .jpbench import RES
from .lmstudio import Stalled, chat

OUT = RES.parent / "jp3"
N_EX = 8
PERSONA = "あなたは親しみやすい日本語で、です・ます調で相談に乗るチャットアシスタントです。"
RULES = ("Always respond in natural conversational Japanese.\nCompressed context is an internal representation.\nDo not imitate its grammar or writing style.")
BLOCK_NOTE = ("The following is machine-compressed historical context.\nUse it only as factual/contextual information.\nDo not imitate its writing style.")
PLAIN_NOTE = "The following is historical context.\nUse it only as factual/contextual information."
STATUS_NOTE = {
    "DONE": "{p}さんは実際に{np}{ta}。すでに起きたことが前提で、声かけはその事実を踏まえるべき",
    "NOT_DONE": "{p}さんは{np}{te}いない(しなかった)。したことにしてはいけない",
    "PLANNED": "{p}さんは{np}{dict}予定・つもりだが、まだ実行していない",
    "WANTED": "{p}さんは{np}{stem}たいと望んでいるが、まだ実行していない",
    "UNDECIDED": "{p}さんは{np}{vol}か迷っていて、まだ決めていない。すでにしたと決めつけてはいけない",
    "HEARSAY": "{p}さんが{np}{dict}という話は聞いただけで、本当かどうか確認できていない。事実と決めつけてはいけない",
    "POSSIBLE": "{p}さんは{np}{dict}かもしれないという可能性があるだけで、確かではない"}
DETAIL = ["本人はけっこう不安そうだった。", "周りにはまだ何も言っていないみたい。", "最近ちょっと元気がないんだよね。", "家族には話したのかな。", "なんだか悩んでる感じだった。"]
USER_TEMPLATES = ["今日はずっと雨で、なんだか気分が重いな。", "週末は映画に行ってきたよ。", "最近ぜんぜん眠れなくて困ってる。", "新しいカフェを見つけたんだ。", "来週は仕事が忙しくなりそう。"]


def build_scenarios(n: int = 35, seed: int = 33, n_ex: int = N_EX) -> List[Dict]:
    rng = random.Random(seed)
    pool = jpdata.make_memories(n * 6, seed=seed)
    by_status = defaultdict(list)
    for m in pool:
        by_status[m.status].append(m)
    out = []
    per = n // 7
    targets = [by_status[s][i] for i in range(per) for s in jpdata.STATUSES]
    used = {m.id for m in targets}
    others = [m for m in pool if m.id not in used]
    rng.shuffle(others)
    ev = {e.key: e for e in jpdata.EVENTS}
    for k, t in enumerate(targets):
        e = ev[t.event]
        f = jpdata.conj(e)
        d = [others[(3 * k + j) % len(others)] for j in range(3)]
        turns = [t.text,                                    # 1 target fact (old)
                 d[0].text,                                  # 2 distractor
                 rng.choice(USER_TEMPLATES),                 # 3 small talk
                 f"{t.person}さんのことなんだけど、" + rng.choice(DETAIL),   # 4 target detail (old)
                 d[1].text,                                  # 5 distractor
                 rng.choice(USER_TEMPLATES),                 # 6 small talk
                 d[2].text,                                  # 7 distractor
                 rng.choice(USER_TEMPLATES)]                 # 8 small talk
        j = 3
        while len(turns) < n_ex:                             # longer histories: more distractor facts and small talk after the target facts
            turns.append(others[(3 * k + j) % len(others)].text if len(turns) % 2 == 0 else rng.choice(USER_TEMPLATES))
            j += 1
        out.append(dict(sid=k, person=t.person, event=t.event, status=t.status, user_turns=turns, question=f"{t.person}さんにどう声をかけたらいいかな？",
                        gold_note=STATUS_NOTE[t.status].format(p=t.person, np=e.np, **f)))
    return out


def variant_files(variant: str):
    if variant == "secf":  # SeCF conditions on the short histories
        return ("histories.jsonl", "gensecf_", "judgesecf_")
    return ("histories_long.jsonl", "genlong_", "judgelong_") if variant == "long" else ("histories.jsonl", "gen_", "judge_")


def gen_histories(model: str, n: int = 35, base_url="http://localhost:1234/v1", log=print, variant: str = "short") -> None:
    """Assistant replies for the user turns, generated by the model from the L0 history so far (short polite replies)."""
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / variant_files(variant)[0]
    have = {json.loads(l)["sid"] for l in path.read_text(encoding="utf-8").splitlines()} if path.exists() else set()
    extra = {"reasoning_effort": "none"} if "gemma" in model else None
    for sc in build_scenarios(n, n_ex=24 if variant == "long" else N_EX):
        if sc["sid"] in have:
            continue
        msgs = [{"role": "system", "content": PERSONA + "返信は1〜2文で、相づち・共感・短い一言を中心にしてください。"}]
        ex = []
        for u in sc["user_turns"]:
            msgs.append({"role": "user", "content": u})
            r = chat(model, "", "", messages=[dict(m) for m in msgs], max_tokens=120, base_url=base_url, extra=extra, deadline=240)
            a = r.text.strip().replace("\n", " ")
            msgs.append({"role": "assistant", "content": a})
            ex.append([u, a])
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(dict(sc, exchanges=ex), ensure_ascii=False) + "\n")
        log(f"history {sc['sid']} done")


def load_histories(variant: str = "short") -> List[Dict]:
    return [json.loads(l) for l in (OUT / variant_files(variant)[0]).read_text(encoding="utf-8").splitlines()]


_conv = None


def l1_text(text: str) -> str:
    global _conv
    if _conv is None:
        _conv = jl1.Converter("sudachi", "m")
    return _conv(text)


SECF_SYSTEM = """日本語の会話の1発話を、LLMの内部メモリ用の意味構造(SeCF)に変換します。出力は構造1行のみ。説明は書かない。
形式: 主体{時:..; event:..; <対象>:{state:..}; decision:true|false|unknown; ..}
- 事実(誰が・いつ・何を・どういう状態か)を保持する。助詞・敬語・相づちは落とす。
- 実行済/未実行/予定/希望/迷い/伝聞/可能性は state か decision で必ず区別して残す(確定していないことを確定にしない)。
- 話者がユーザーの発話は主体を「ユーザー」とする。アシスタントの返事は「アシスタント{act:共感|質問|助言; 内容:..}」とする。

例:
入力: 昨日、田中さんと久しぶりに話した。田中さんは会社を辞めようか迷っているが、まだ決めていない。
出力: 田中{時:昨日; event:会話; 退職:{state:検討}; decision:false}
入力: 佐藤さんが旅行に行ったという話は聞いただけで、本当かどうか分からない。
出力: 佐藤{旅行:{state:伝聞; 確認:false}; decision:unknown}
入力: 今日はずっと雨で、なんだか気分が重いな。
出力: ユーザー{時:今日; 天気:雨; 気分:重い}
入力: それは気が重くなりますよね。無理せず過ごしてくださいね。
出力: アシスタント{act:共感; 内容:{気分:重い; 助言:無理しない}}"""
_secf_cache: Optional[Dict[str, str]] = None
SECF_MODEL = "google/gemma-4-12b"


def secf_text(text: str, model: str = SECF_MODEL, base_url="http://localhost:1234/v1") -> str:
    """SeCF-L1 of one utterance: LLM-generated semantic structure (cached; temperature 0)."""
    global _secf_cache
    path = OUT / "secf_cache.jsonl"
    if _secf_cache is None:
        _secf_cache = {}
        if path.exists():
            for l in path.read_text(encoding="utf-8").splitlines():
                r = json.loads(l)
                _secf_cache[r["text"]] = r["secf"]
    if text in _secf_cache:
        return _secf_cache[text]
    r = chat(model, SECF_SYSTEM, f"入力: {text}\n出力:", max_tokens=160, base_url=base_url, extra={"reasoning_effort": "none"}, deadline=120, timeout=140)
    out = r.text.strip().split("\n")[0].strip()
    out = re.sub(r"^出力[:：]\s*", "", out)
    _secf_cache[text] = out
    OUT.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(dict(text=text, secf=out, ms=round(r.total * 1000)), ensure_ascii=False) + "\n")
    return out


def prep_secf(variant: str = "short", log=print) -> None:
    """Pre-compute the SeCF form of every user/assistant utterance of the histories."""
    n = 0
    for h in load_histories(variant):
        for u, a in h["exchanges"]:
            secf_text(u)
            secf_text(a)
        n += 1
        if n % 5 == 0:
            log(f"secf converted {n} histories")


MARKER_EXPL = {"た": "済", "たい": "希望", "ない": "否定", "らしい": "伝聞", "かも": "可能性", "みたい": "推量"}
LEGEND = "圧縮された履歴の記法: 語は空白区切り、/ は文の区切り。た=過去・完了、たい=願望、ない=否定、らしい=伝聞、かも=可能性、みたい=推量。"


def l1_expl(text: str) -> str:
    """SCF-L1 with the functional markers replaced by self-explanatory words (済/希望/否定/伝聞/可能性/推量); whole space-separated tokens only."""
    return " ".join(MARKER_EXPL.get(w, w) for w in l1_text(text).split(" "))


# ---------------------------------------------------------------------------------------------------------- conditions
def cond_table(variant: str = "short") -> Dict[str, Dict]:
    if variant == "secf":  # SeCF mirror of the short conditions: C = hybrid (message list), E = full (c=8), G = isolated (tag + instruction)
        c = {}
        for k in (2, 4, 6, 7, 8):
            c[f"C_c{k}"] = dict(family="role", c=k, form="secf")
        for k in (2, 4, 6, 7, 8):
            c[f"G_c{k}"] = dict(family="tag", c=k, instr=True, form="secf")
        c["G0_noinstr_c6"] = dict(family="tag", c=6, instr=False, form="secf")
        c["GP2_recent_then_block_c6"] = dict(family="tag", c=6, instr=True, order="recent_first", form="secf")
        c["GP3_block_persona_c6"] = dict(family="tag", c=6, instr=True, persona_after=True, form="secf")
        return c
    if variant == "long":  # 24 exchanges: old 16 / 24 exchanges compressed
        return {"A_base": dict(family="role", c=0), "B_c16": dict(family="role", c=16), "B_c24": dict(family="role", c=24),
                "T0_plain": dict(family="tag", c=16, instr=True, l1=False), "D_c16": dict(family="tag", c=16, instr=True), "D_c24": dict(family="tag", c=24, instr=True),
                "P2_recent_then_block_c16": dict(family="tag", c=16, instr=True, order="recent_first")}
    c = {"A_base": dict(family="role", c=0)}
    for k in (2, 4, 6, 7, 8):
        c[f"B_c{k}"] = dict(family="role", c=k)
    c["T0_plain"] = dict(family="tag", c=6, instr=True, l1=False)       # same wrapper/instruction, old history stays L0 (control)
    for k in (2, 4, 6, 7, 8):
        c[f"D_c{k}"] = dict(family="tag", c=k, instr=True)
    c["D0_noinstr_c6"] = dict(family="tag", c=6, instr=False)
    c["P2_recent_then_block_c6"] = dict(family="tag", c=6, instr=True, order="recent_first")
    c["P3_block_persona_c6"] = dict(family="tag", c=6, instr=True, persona_after=True)
    return c


def build_messages(sc: Dict, spec: Dict, nonce: str):
    """-> (messages, conv_ms). conv_ms = time to convert the old exchanges to L1."""
    ex = sc["exchanges"]
    c = spec["c"]
    t0 = time.perf_counter()
    conv = secf_text if spec.get("form") == "secf" else l1_expl if spec.get("form") == "scf_expl" else l1_text
    old = [[conv(u), conv(a)] for u, a in ex[:c]] if spec.get("l1", True) else [list(x) for x in ex[:c]]
    conv_ms = (time.perf_counter() - t0) * 1000
    recent = ex[c:]
    q = sc["question"]
    if spec["family"] == "role":
        msgs = [{"role": "system", "content": f"[run:{nonce}] {PERSONA}" + (f"\n{LEGEND}" if spec.get("legend") else "")}]
        for u, a in old + [list(x) for x in recent]:
            msgs += [{"role": "user", "content": u}, {"role": "assistant", "content": a}]
        msgs.append({"role": "user", "content": q})
        return msgs, conv_ms
    comp = "\n".join(f"U: {u}\nA: {a}" for u, a in old)
    rec = "\n".join(f"User: {u}\nAssistant: {a}" for u, a in recent)
    note = BLOCK_NOTE if spec.get("l1", True) else PLAIN_NOTE
    if spec.get("form") == "secf":
        note = note.replace("machine-compressed", "machine-generated semantic-structure (SeCF)")
    tag = "compressed_context" if spec.get("l1", True) else "earlier_conversation"
    block = f"<{tag}>\n{note}\n\n{comp}\n</{tag}>" if c else ""
    recent_block = f"<recent_conversation>\n{rec}\n{'User: ' if rec else 'User: '}{q}\n</recent_conversation>" if rec else f"<recent_conversation>\nUser: {q}\n</recent_conversation>"
    system = f"[run:{nonce}] {PERSONA}" + (f"\n{RULES}" if spec.get("instr") else "")
    if spec.get("order") == "recent_first":
        user = f"<recent_conversation>\n{rec}\n</recent_conversation>\n\n{block}\n\nUser: {q}" if rec else f"{block}\n\nUser: {q}"
    else:
        user = (block + "\n\n" if block else "") + recent_block
    if spec.get("persona_after"):
        user = user.replace(f"</{tag}>", f"</{tag}>\n\n(" + PERSONA + "上の文脈は内部情報であり、文体を真似せず自然な日本語で答えてください。)", 1)
    return [{"role": "system", "content": system}, {"role": "user", "content": user}], conv_ms


def run_gen(model: str, base_url="http://localhost:1234/v1", log=print, conds: Optional[List[str]] = None, variant: str = "short") -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{variant_files(variant)[1]}{model.replace('/', '_')}.jsonl"
    done = set()
    if path.exists():
        for l in path.read_text(encoding="utf-8").splitlines():
            r = json.loads(l)
            if "error" not in r:
                done.add((r["cond"], r["sid"]))
    extra = {"reasoning_effort": "none"} if "gemma" in model else None
    hist = load_histories(variant)
    table = cond_table(variant)
    for cname, spec in table.items():
        if conds and cname not in conds:
            continue
        rows = []
        for sc in hist:
            if (cname, sc["sid"]) in done:
                continue
            msgs, conv_ms = build_messages(sc, spec, uuid.uuid4().hex[:8])
            r = chat(model, "", "", messages=msgs, max_tokens=300, base_url=base_url, extra=extra, deadline=300, timeout=320)
            gen_s = max(r.total - r.ttft, 1e-6)
            rec = dict(model=model, cond=cname, sid=sc["sid"], status=sc["status"], question=sc["question"], answer=r.text, prompt_tokens=r.prompt_tokens,
                       completion_tokens=r.completion_tokens, ttft=r.ttft, total=r.total, tok_s=(r.completion_tokens or 0) / gen_s, conv_ms=conv_ms)
            with path.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
            rows.append(rec)
        if rows:
            log(f"{cname}: n={len(rows)} prompt={sum(r['prompt_tokens'] for r in rows) / len(rows):.0f}tok ttft={sum(r['ttft'] for r in rows) / len(rows):.1f}s "
                f"len={sum(len(r['answer']) for r in rows) / len(rows):.0f}chars")


# ---------------------------------------------------------------------------------------------------------- style metrics
_PUNCT = "。！？!?、,.…「」『』()（）[]【】~〜・:：;；/／"
_SENT = re.compile(r"[。！？!?\n]+")
_L1_LABEL = re.compile(r"(?<![ぁ-んァ-ヶー一-龥])(未|有|無|済|否)(?![ぁ-んァ-ヶー一-龥])")
_STRUCT = re.compile(r"[{}\[\]]|[A-Za-z_]+\s*:\s*|[^\s。、]{1,6}:[^\s。、/]{1,8}|;")
_BULLET = re.compile(r"^\s*([-*・•]|\d+[.)．])\s")
_FIELD = re.compile(r"\b(event|state|decision|act|status|true|false|unknown)\b|主体|アシスタント\{|ユーザー\{|時:")
_POLITE_END = ("です", "ます", "ません", "でした", "ました", "でしょう", "ください", "ましょう", "ですね", "ますね", "ですよ", "ますよ", "ですか", "ますか")


def style_metrics(text: str) -> Dict[str, float]:
    sud = jlvar.sud()
    sents = [s.strip() for s in _SENT.split(text) if s.strip()]
    n_chars = max(len(text), 1)
    toks_all, last_pos, polite, telegraphic, labels = [], [], 0, 0, len(_L1_LABEL.findall(text))
    for s in sents:
        toks = [t for t in sud.analyze(s) if t.pos not in ("補助記号", "空白")]
        toks_all += toks
        if not toks:
            continue
        last = toks[-1]
        last_pos.append(last.pos)
        if s.endswith(_POLITE_END) or any(s.rstrip("。！？!?ね よ").endswith(e) for e in _POLITE_END):
            polite += 1
        if len(toks) >= 3 and not any(t.pos in ("助詞", "助動詞") for t in toks):
            telegraphic += 1
    nt = max(len(toks_all), 1)
    ns = max(len(sents), 1)
    return dict(
        chars=len(text), sentences=len(sents), avg_sentence_chars=len(text) / ns,
        particle_rate=sum(t.pos == "助詞" for t in toks_all) / nt, noun_rate=sum(t.pos in ("名詞", "代名詞") for t in toks_all) / nt, verb_rate=sum(t.pos == "動詞" for t in toks_all) / nt,
        sentence_final_rate=sum(p in ("助動詞", "助詞", "動詞", "形容詞", "形状詞") for p in last_pos) / ns, taigen_rate=sum(p in ("名詞", "代名詞") for p in last_pos) / ns,
        polite_rate=polite / ns, telegraphic_rate=telegraphic / ns, l1_label_per_100=labels / n_chars * 100, slash_per_100=(text.count("/") + text.count("→")) / n_chars * 100,
        struct_per_100=len(_STRUCT.findall(text)) / n_chars * 100, bullet_rate=sum(bool(_BULLET.match(l)) for l in text.split("\n")) / max(len([l for l in text.split("\n") if l.strip()]), 1),
        field_per_100=len(_FIELD.findall(text)) / n_chars * 100)


# ---------------------------------------------------------------------------------------------------------- judge
JUDGE_SYSTEM = "あなたは日本語の回答品質を厳密に採点する審査員です。出力はJSONのみ。"
JUDGE_TMPL = """次はチャットアシスタントの回答です。回答を4項目で1〜5の整数で採点してください。

[状況(正しい事実)] {gold}
[ユーザーの質問] {question}
[回答]
{answer}

採点基準:
- 自然さ: 現代の自然な話し言葉・書き言葉の日本語として読めるか(5=完全に自然、1=不自然)
- 意味保持: 状況(正しい事実)に合致し、矛盾や決めつけがないか(5=完全に合致、1=事実と矛盾または無関係)
- 会話らしさ: 相談相手として人に語りかける会話文になっているか(5=会話として自然、1=メモ・箇条書き・電報のよう)
- L1文体汚染: 助詞の欠落・体言止めの連続・名詞の羅列・「未」「有」などの記号的表現など、圧縮メモ風の文体がどれだけ混入しているか(5=強く混入、1=全くない)

出力形式: {{"自然さ":数,"意味保持":数,"会話らしさ":数,"L1文体汚染":数}}"""


def judge(model: str, gen_model: str, base_url="http://localhost:1234/v1", log=print, variant: str = "short") -> None:
    """Blind scoring (the judge sees the answer only, never the condition) by a model different from the generator."""
    src = OUT / f"{variant_files(variant)[1]}{gen_model.replace('/', '_')}.jsonl"
    path = OUT / f"{variant_files(variant)[2]}{model.replace('/', '_')}_on_{gen_model.replace('/', '_')}.jsonl"
    rows = [json.loads(l) for l in src.read_text(encoding="utf-8").splitlines()]
    rows = [r for r in rows if "error" not in r]
    sc = {h["sid"]: h for h in load_histories(variant)}
    done = set()
    if path.exists():
        for l in path.read_text(encoding="utf-8").splitlines():
            r = json.loads(l)
            done.add((r["cond"], r["sid"]))
    random.Random(1).shuffle(rows)
    extra = {"reasoning_effort": "none"} if "gemma" in model else None
    nt = "\n/no_think" if "qwen3" in model else ""
    n = 0
    for r in rows:
        if (r["cond"], r["sid"]) in done:
            continue
        prompt = JUDGE_TMPL.format(gold=sc[r["sid"]]["gold_note"], question=r["question"], answer=r["answer"]) + nt
        j = chat(model, f"[j:{uuid.uuid4().hex[:6]}] {JUDGE_SYSTEM}", prompt, max_tokens=100, base_url=base_url, extra=extra, deadline=120, timeout=140)
        m = re.search(r"\{.*?\}", j.text, re.S)
        try:
            d = json.loads(m.group(0))
            scores = {k: int(d[k]) for k in ("自然さ", "意味保持", "会話らしさ", "L1文体汚染")}
        except Exception:
            scores = None
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(dict(cond=r["cond"], sid=r["sid"], raw=j.text[:120], scores=scores), ensure_ascii=False) + "\n")
        n += 1
        if n % 50 == 0:
            log(f"judged {n}")


if __name__ == "__main__":
    mode = sys.argv[1]
    variant = sys.argv[-1] if sys.argv[-1] in ("long", "secf") else "short"
    try:
        if mode == "hist":
            gen_histories(sys.argv[2], n=21 if variant == "long" else 35, log=lambda s: print(s, flush=True), variant=variant)
        elif mode == "prep_secf":
            prep_secf("short", log=lambda s: print(s, flush=True))
        elif mode == "gen":
            run_gen(sys.argv[2], log=lambda s: print(s, flush=True), variant=variant)
        elif mode == "judge":
            judge(sys.argv[2], sys.argv[3], log=lambda s: print(s, flush=True), variant=variant)
    except Stalled as e:
        print(f"STALLED: {e}", flush=True)
        sys.exit(75)
